### ISSUE TITLE
Unstructured.

### ISSUE THREAD

**Issue by Miolus** [PlatinLang-Foundation/PlatinLang#2]
Hi. I tried adding some features, but I wasn't able to find any entry points for new syntax.. How does it work? / Where are the entry points?

**Comment by TheDomCraft** [comment]
You can find the Syntax Definition at platinlang.py at line 170 

![Screenshot_20210324-093253_GitHub.png](https://user-images.githubusercontent.com/64731738/112279237-fd1be400-8c83-11eb-8892-02245bcdf05f.png)
